name: Kubernetes Manifest Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
          sudo mv kubeconform /usr/local/bin/

      - name: Validate manifests
        run: |
          find . -type f \( -name "*.yml" -o -name "*.yaml" \) ! -path "./.github/*" ! -path "./helm/Chart.yaml" | xargs kubeconform -strict -summary
